[package]
name = "present-cipher"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

[dependencies.bitvec]
version = "1.0.1"
default-features = false
features = [
    "alloc",
    # "atomic",
    # "serde",
    # "std",
]
